ssh_authorized_keys:
- ssh-rsa ""
- github:rizviz
write_files:
- encoding: ""
  content: |-
    #!/bin/bash
    echo hello from `uname -a`
  owner: root
  path: /etc/rc.local
  permissions: '0755'
hostname: k3os
run_cmd:
- "echo hi && echo bye"
boot_cmd:
- "echo hi && echo bye"
init_cmd:
- "echo hi && echo bye"

k3os:
  data_sources:
  - aws
  - cdrom
  modules:
  - kvm
  - nvme
  sysctl:
    kernel.printk: 4 4 1 7
    kernel.kptr_restrict: 1
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  wifi:
  - ssid: home
    passphrase: mypassword
  - ssid: nothome
    passphrase: somethingelse
  password: rancher
  server_url: https://someserver:6443
  token: TOKEN_VALUE
  labels:
    region: us-west-1
    somekey: somevalue
  k3s_args:
  - server
  - "--disable-agent"
  environment:
    http_proxy: http://myserver
    http_proxys: http://myserver
  taints:
  - key1=value1:NoSchedule
  - key1=value1:NoExecute
